FROM python

RUN apt-get update -y && apt-get upgrade -y

RUN ["mkdir", "/app"]

WORKDIR /app

COPY ./wait-for-it.sh .

COPY ./requirements.txt .

RUN pip install -r  requirements.txt

COPY ./route_guide/ .

CMD ["python", "route_guide_client.py"]