# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\"#\n\x07OrderId\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x0c\n\x04GUID\x18\x02 \x01(\t\"U\n\x05Order\x12\x0e\n\x06UserId\x18\x01 \x01(\x05\x12\x11\n\tProductId\x18\x02 \x01(\x05\x12\r\n\x05\x43ount\x18\x03 \x01(\x05\x12\x0c\n\x04Name\x18\x04 \x01(\t\x12\x0c\n\x04GUID\x18\x05 \x01(\t2.\n\x0cOrderService\x12\x1e\n\x08GetOrder\x12\x08.OrderId\x1a\x06.Order\"\x00\x62\x06proto3')



_ORDERID = DESCRIPTOR.message_types_by_name['OrderId']
_ORDER = DESCRIPTOR.message_types_by_name['Order']
OrderId = _reflection.GeneratedProtocolMessageType('OrderId', (_message.Message,), {
  'DESCRIPTOR' : _ORDERID,
  '__module__' : 'order_service_pb2'
  # @@protoc_insertion_point(class_scope:OrderId)
  })
_sym_db.RegisterMessage(OrderId)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'order_service_pb2'
  # @@protoc_insertion_point(class_scope:Order)
  })
_sym_db.RegisterMessage(Order)

_ORDERSERVICE = DESCRIPTOR.services_by_name['OrderService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERID._serialized_start=23
  _ORDERID._serialized_end=58
  _ORDER._serialized_start=60
  _ORDER._serialized_end=145
  _ORDERSERVICE._serialized_start=147
  _ORDERSERVICE._serialized_end=193
# @@protoc_insertion_point(module_scope)
