# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\"\"\n\x06UserId\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x0c\n\x04GUID\x18\x02 \x01(\t\"\"\n\x04User\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0c\n\x04GUID\x18\x02 \x01(\t2*\n\x0bUserService\x12\x1b\n\x07GetUser\x12\x07.UserId\x1a\x05.User\"\x00\x62\x06proto3')



_USERID = DESCRIPTOR.message_types_by_name['UserId']
_USER = DESCRIPTOR.message_types_by_name['User']
UserId = _reflection.GeneratedProtocolMessageType('UserId', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:UserId)
  })
_sym_db.RegisterMessage(UserId)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERID._serialized_start=22
  _USERID._serialized_end=56
  _USER._serialized_start=58
  _USER._serialized_end=92
  _USERSERVICE._serialized_start=94
  _USERSERVICE._serialized_end=136
# @@protoc_insertion_point(module_scope)
