FROM python

RUN apt-get update -y && apt-get upgrade -y

RUN ["mkdir", "/app"]

WORKDIR /app

COPY ./wait-for-it.sh ./requirements.txt ./test_app/grpc_tracer.py ./

RUN pip install -r  requirements.txt

COPY  ./test_app/user_service*.py ./

CMD ["python", "user_service.py"]